"""
1、关于操作的列表
2、用来进行检测用例
"""
FUNLIST = {
    "打开链接": 'open',
    "返回上一个页面": 'back',
    "前进下一个页面": 'forward',
    "刷新页面": 'refresh',
    "最大化窗口": 'max',
    "关闭浏览器": 'quit',
    "获取弹窗文本": 'get_alert_text',
    "弹窗点击确定": 'alert_accept',
    "弹窗点击取消": 'alert_dismiss',
    "等待X毫秒": 'sleep',
    "点击_id": 'click_id',
    "点击_selector": 'click_selector',
    "点击_xpath": 'click_xpath',
    "输入_id": 'type_id',
    "输入_selector": 'type_selector',
    "输入_xpath": 'type_xpath',
    "清空元素_id": 'clear_id',
    "清空元素_selector": 'clear_selector',
    "清空元素_xpath": 'clear_xpath',
    "右键_id": 'right_click_id',
    "右键_selector": 'right_click_selector',
    "右键_xpath": 'right_click_xpath',
    "移动到元素_id": 'move_id',
    "移动到元素_selector": 'move_selector',
    "移动到元素_xpath": 'move_xpath',
    "移动到元素并按住_id": 'move_hold_id',
    "移动到元素并按住_selector": 'move_hold_selector',
    "移动到元素并按住_xpath": 'move_hold_xpath',
    "拖动一个元素到另一个元素_id": 'drag_and_drop_id',
    "拖动一个元素到另一个元素_selector": 'drag_and_drop_selector',
    "拖动一个元素到另一个元素_xpath": 'drag_and_drop_xpath',
    "执行一段js": 'exe_js',
    "进入frame_id": 'in_frame_id',
    "进入frame_selector": 'in_frame_selector',
    "进入frame_xpath": 'in_frame_xpath',
    "从frame出来": 'out_frame',
    "获取文本值_id": 'get_text_id',
    "获取文本值_selector": 'get_text_selector',
    "获取文本值_xpath": 'get_text_xpath',
    "获取属性值_id": 'get_attr_id',
    "获取属性值_selector": 'get_attr_selector',
    "获取属性值_xpath": 'get_attr_xpath',
    "检查点_文本一致_id": 'assert_test_agreement_id',
    "检查点_文本一致_selector": 'assert_test_agreement_selector',
    "检查点_文本一致_xpath": 'assert_test_agreement_xpath',
    "检查点_属性一致_id": 'assert_attr_agreement_id',
    "检查点_属性一致_selector": 'assert_attr_agreement_selector',
    "检查点_属性一致_xpath": 'assert_attr_agreement_xpath',
    "检查点_变量一致": 'assert_var_agreement',
    "检查点_文本包含_id": 'assert_test_contain_id',
    "检查点_文本包含_selector": 'assert_test_contain_selector',
    "检查点_文本包含_xpath": 'assert_test_contain_xpath',
    "检查点_属性包含_id": 'assert_attr_contain_id',
    "检查点_属性包含_selector": 'assert_attr_contain_selector',
    "检查点_属性包含_xpath": 'assert_attr_contain_xpath',
    "检查点_变量包含": 'assert_var_contain',
    "输出控制台": 'print',
}

# 参数处理列表
PARPROLIST = {
    'MD5': 'MD5',
    "变量": 'var',
}
